version: '3.8'

services:
  # Backend API
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: cloudops-backend
    environment:
      NODE_ENV: development
      PORT: 5000
      DB_HOST: ${DB_HOST:-your-rds-endpoint.region.rds.amazonaws.com}
      DB_PORT: 5432
      DB_NAME: cloudops_demo
      DB_USER: postgres
      DB_PASSWORD: ${DB_PASSWORD:-your-password}
    ports:
      - "5000:5000"
    volumes:
      - ./backend:/app
      - /app/node_modules
    networks:
      - cloudops-network
    restart: unless-stopped

  # Frontend React App
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: cloudops-frontend
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      - REACT_APP_API_URL=http://localhost:5000/api
    networks:
      - cloudops-network
    restart: unless-stopped

networks:
  cloudops-network:
    driver: bridge