apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: cloudops-demo
  labels:
    app: cloudops-demo
data:
  # Database configuration (AWS RDS)
  DB_HOST: "cloudops-demo-postgres.cne4ekkyyoz0.us-east-1.rds.amazonaws.com"  # Replace with your RDS endpoint
  DB_PORT: "5432"
  DB_NAME: "cloudops_demo"
  DB_USER: "postgres"
  
  # Backend configuration
  NODE_ENV: "production"
  PORT: "5000"
  
  # Frontend configuration
  REACT_APP_API_URL: "/api"