apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: cloudops-demo
  labels:
    app: cloudops-demo
type: Opaque
data:
  # Base64 encoded values
  # password -> cGFzc3dvcmQ=
  # postgres -> cG9zdGdyZXM=
  POSTGRES_PASSWORD: YXNuYXNoYW1lZWw=
  POSTGRES_USER: cG9zdGdyZXM=
  DB_PASSWORD: YXNuYXNoYW1lZWw=
